[package]
name = "libgssapi"
version = "0.4.1"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A safe binding to gssapi"
homepage = "https://github.com/estokes/libgssapi"
documentation = "https://estokes.github.io/libgssapi/libgssapi/index.html"
repository = "https://github.com/estokes/libgssapi"
keywords = ["gssapi", "sspi", "kerberos", "krb5", "authentication"]
categories = ["api-bindings", "authentication", "cryptography", "os::unix-apis"]

[dependencies]
bytes = "0.5"
libgssapi-sys = { path = "../libgssapi-sys" }
parking_lot = "0.10"
bitflags = "1.2"
lazy_static = "1.4"

[[example]]
name = "krb5_iov"
required-features = ["iov"]

[features]
iov = []
